n = 3

nodes = [
  { :name => "vpn", :ip => "192.168.122.11", :mem => 1024, :cpu => 1 },
  { :name => "web", :ip => "192.168.122.12", :mem => 512, :cpu => 1 },
  { :name => "db", :ip => "192.168.122.13", :mem => 512, :cpu => 1 },
]

Vagrant.configure("2") do |config|
    nodes.each do |vm|
      config.vm.define vm[:name] do |node|
      # defines VM'S OS and hostname
      node.vm.box = "almalinux/9"
      node.vm.hostname = vm[:name]

      # defines bridge connection to host ethernet NIC
      node.vm.network "private_network",
        ip: vm[:ip],
        libvirt__network_name: "default",
        libvirt__forward_mode: "nat"

      # defines VM's virtual resources
      node.vm.provider :libvirt do |lv|
        # defines VM's vRAM and vCUP
        lv.memory = vm[:mem]
        lv.cpus = vm[:cpu]

        lv.qemu_use_session = false
        lv.uri = "qemu:///system"

        # defines a headless VM with no GUI support
        lv.video_type = "none"
        lv.graphics_type = "none"
      end
    end
  end
end
