n = 3

Vagrant.configure("2") do |config|
    (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      # defines VM'S OS and hostname
      node.vm.box = "almalinux/9"
      node.vm.hostname = "onprem-node-#{i}"
      
      # defines bridge connection to host ethernet NIC
      node.vm.network "private_network",
        ip: "192.168.122.#{10+i}",
        libvirt__network_name: "default",
        libvirt__forward_mode: "nat"

      # defines VM's virtual resources
      node.vm.provider :libvirt do |lv|
        # defines VM's vRAM and vCUP
        lv.memory = 1024
        lv.cpus = 1

        lv.qemu_use_session = false
        lv.uri = "qemu:///system"

        # defines a headless VM with no GUI support
        lv.video_type = "none"
        lv.graphics_type = "none"
      end
    end
  end
end
